# Generated by Django 4.2 on 2023-04-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0003_add_goals_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcomment',
            name='category',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='comments',
                to='goals.goalcategory',
            ),
            preserve_default=False,
        ),
    ]
