name: Build

on:
  push:
    branches-ignore:
      - main
      - dev_38

jobs:
  test: # для тестов
    runs-on: ubuntu-latest
    container: python:3.10.4-slim
    env:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      SECRET_KEY: 'iucbIWLeOWspT4vM4K2Ie'
      VK_OAUTH2_KEY: 1234567
      VK_OAUTH2_SECRET: 'VK_OAUTH2_SECRET'
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install "poetry==1.4.2"
          poetry config virtualenvs.create true
          poetry install -n --without dev
      - name: Run tests
        run: poetry run pytest . -v

  build:
    needs: test # добавлено с тестами
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todolist:${{ env.BRANCH_NAME }}
